query lastIssues($num: Int!) {
  viewer {
    login
  }
  repository(owner: "matrix-org", name: "matrix-spec-proposals") {
    pullRequest(number: $num) {
      id
      title
      state
      lastEditedAt,
      createdAt,
      isDraft,
      closedAt,
      latestReviews(first: 20) {
        nodes {
          id
          author {
            login
            avatarUrl
          }
          state
          body
        }
      }
			reviewThreads(first: 20) {
				nodes {
          id,
					comments(first: 5) {
						nodes {
							id,
							author {
								avatarUrl,
								login
							},
							body,
							createdAt,
							minimizedReason,
						}
					}
				}
			}
      labels(first: 10) {
        nodes {
          id
          name
          color
          description
        }
      }
      url
      author {
        avatarUrl
        login
      }
      body
      headRef {
        name
      }
      headRepository {
        nameWithOwner,
      }
      files(last: 30) {
        nodes {
          path
        }
      }
      comments(last: 100) {
        totalCount,
        pageInfo {
          hasNextPage
        }
        nodes {
          id,
          author {
            avatarUrl,
            login
          },
          body,
          createdAt,
          minimizedReason,
        }
      }
    }
  }
}